apiVersion: v1
kind: Service
metadata:
  name:  api-web-${WORKSPACE}
  namespace: ${NAMESPACE}
  labels:
    app: api-web-${WORKSPACE}
spec:
  type: ClusterIP
  selector:
    app: api-web-${WORKSPACE}
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-web-${WORKSPACE}-dp
  namespace: ${NAMESPACE}
  labels:
    app: api-web-${WORKSPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-web-${WORKSPACE}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: api-web-${WORKSPACE}
    spec:
      containers:
        - name: api-gateway-isicom-web
          image: gitlab.cpsaa.com.pe:5050/cantera/proyecto-isicom/proyecto-isicom-web/isicom-backend/api-gateway-isicom-web/${DOCKER_SUB_LEVEL}:${VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
          - name: storage-tokens
            mountPath: /var/tokens
          - name: storage-temp
            mountPath: /var/temp
      volumes:
      - name: storage-tokens
        persistentVolumeClaim:
          claimName: secrets-storage-pvc
      - name: storage-temp
        persistentVolumeClaim:
          claimName: temp-storage-pvc
      imagePullSecrets:
        - name: gitlab-isicom-registry
        